<font size = 5><b> Generate a random 5×4 matrix X of rank 2 where every element of X is non-negative.  Use Lee-Seung’s multiplicative update algorithm to factorize this matrix as UV where U∈R5×2+ and V∈R2×4+.  Study the performance of the algorithm using different initializations of U and V</b></font>

In [49]:
import numpy as np

In [50]:
# Rank of X is 2
X = np.array([[1,5,2,6],[3,1,6,1],[7,7,14,8],[9,3,18,3],[5,25,10,30]])

In [51]:
X.shape

(5, 4)

In [52]:
from numpy.linalg import matrix_rank
matrix_rank(X)

2

In [53]:
# Random U,V
U = np.random.random((5,2))*10
V = np.random.random((2,4))*10

In [54]:
def error(U,V,X):
    E = X - (U @ V)
    return np.sum(E*E)
epochs = 0
while error(U,V,X) > 1e-6:
    # Multiplicative Update Rule
    U = (U * (X@np.transpose(V))) /(U@V@np.transpose(V)) 
    V = (V * (np.transpose(U)@X)) /(np.transpose(U)@U@V) 
    epochs = epochs + 1
print("Error == ",error(U,V,X))
print("Epochs == ",epochs)

Error ==  8.548273067255597e-07
Epochs ==  67


In [55]:
X

array([[ 1,  5,  2,  6],
       [ 3,  1,  6,  1],
       [ 7,  7, 14,  8],
       [ 9,  3, 18,  3],
       [ 5, 25, 10, 30]])

In [56]:
U@V

array([[ 0.99999367,  4.99999962,  2.00001548,  5.99999237],
       [ 3.0000533 ,  0.9997052 ,  6.00008551,  0.99969085],
       [ 7.0000425 ,  6.99987197, 14.00007094,  7.99993914],
       [ 8.99996745,  3.0004132 , 17.99987161,  3.00066196],
       [ 4.99996836, 24.99999812, 10.00007738, 29.99996184]])

<font size = 4><b> NMF from Scipy</b></font>

In [42]:
rank = 2
from sklearn.decomposition import NMF
model = NMF(n_components=rank, init='random', random_state=0)
U1 = model.fit_transform(X)
V1 = model.components_

In [43]:
error(U1,V1,X)

2.3320332034618876e-06

In [44]:
X

array([[ 1,  5,  2,  6],
       [ 3,  1,  6,  1],
       [ 7,  7, 14,  8],
       [ 9,  3, 18,  3],
       [ 5, 25, 10, 30]])

In [45]:
U1@V1

array([[ 0.99999945,  5.00006344,  1.99999889,  5.99993681],
       [ 3.00000045,  0.99999058,  6.00000091,  1.0003975 ],
       [ 6.99999773,  7.00004711, 13.99999547,  8.00073505],
       [ 9.00000136,  2.99997173, 18.00000272,  3.00119251],
       [ 4.99999723, 25.00031719,  9.99999447, 29.99968405]])

In [46]:
U1.shape

(5, 2)

In [47]:
V1.shape

(2, 4)